#!/usr/bin/env python
"""Generate colab/bootstrap.ipynb.

The notebook is a build artifact, never a source of truth (ROADMAP section 7).
Edit this generator and re-run it; do not edit the .ipynb by hand. Every cell
either calls a script in this repository or performs an environment step that
cannot live in a script (Drive mount, runtime check).

The generated notebook clones a PINNED commit. An unpinned clone would make a
Colab result unattributable to a repository state, which breaks the rule that
every number traces to something reproducible.

A note on the pin, so nobody chases it in circles: regenerating writes a new
notebook, and committing that notebook creates a commit *after* the one it pins.
The notebook therefore names the commit just before its own. That is correct and
harmless — the pinned commit contains all the code Colab runs, and the only later
change is the notebook file itself, which Colab does not execute from the clone.
Regenerate when the *code* changes, not to chase your own tail.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "colab" / "bootstrap.ipynb"
REPO_URL = "https://github.com/AmeyaKI/minispatial.git"


def _current_commit() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=REPO_ROOT,
            capture_output=True, text=True, check=True,
        )
        return out.stdout.strip()
    except (subprocess.CalledProcessError, OSError):
        return "UNKNOWN"


def _md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def _code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


def build(commit: str, repo_url: str) -> dict:
    cells = [
        _md(
            "# minispatial — Colab bootstrap\n"
            "\n"
            "**Generated by `scripts/make_bootstrap_notebook.py`. Do not edit this "
            "notebook by hand** — edit the generator and re-run it.\n"
            "\n"
            f"Pinned commit: `{commit}`\n"
            "\n"
            "Run the cells in order. Every step prints what it did; nothing important "
            "exists only in this notebook's output — results are written to JSON under "
            "`results/runs/` and copied to Drive.\n"
        ),
        _md("## 1. Check the runtime\n\nRecord what hardware Colab gave you; it belongs "
            "in the run's provenance."),
        _code(
            "import subprocess, sys, platform, json\n"
            "print('python', platform.python_version())\n"
            "print(subprocess.run(['nvidia-smi','--query-gpu=name,memory.total',\n"
            "                      '--format=csv,noheader'],\n"
            "                     capture_output=True, text=True).stdout.strip() or 'NO GPU')\n"
        ),
        _md("## 2. Mount Drive\n\nCheckpoints and cached logits persist here; the Colab "
            "filesystem does not."),
        _code(
            "from google.colab import drive\n"
            "drive.mount('/content/drive')\n"
            "DRIVE = '/content/drive/MyDrive/minispatial'\n"
            "import os; os.makedirs(DRIVE, exist_ok=True)\n"
            "print('artifacts will be written to', DRIVE)\n"
        ),
        _md("## 3. Clone the pinned commit\n\nPinning is what makes a result attributable "
            "to a repository state."),
        _code(
            f"COMMIT = {commit!r}\n"
            f"REPO   = {repo_url!r}\n"
            "!git clone -q $REPO /content/minispatial || true\n"
            "%cd /content/minispatial\n"
            "!git fetch -q origin && git checkout -q $COMMIT\n"
            "!git rev-parse --short HEAD\n"
        ),
        _md("## 4. Install\n\nThe `train` extra only. Core ML and MLX are Mac-side and are "
            "deliberately not installed here."),
        _code(
            "!pip install -q -e '.[train]'\n"
            "import importlib.metadata as md\n"
            "for p in ('torch','terratorch','numpy'):\n"
            "    print(p, md.version(p))\n"
        ),
        _md("## 5. Sanity: the band contract resolves\n\nIf this fails, stop — every "
            "downstream number would be computed on the wrong bands."),
        _code(
            "from minispatial.data.bands import load_band_spec\n"
            "spec = load_band_spec()\n"
            "print('bands:', spec.band_names)\n"
            "print('constant_scale:', spec.constant_scale, 'ignore_index:', spec.ignore_index)\n"
            "print('normalization from:', spec.normalization_source)\n"
        ),
        _md("## 6. Get Sen1Floods11\n\n"
            "Hand-labeled subset only: 446 chips, 1.02 GB. Resolved bucket and paths are in "
            "`DATA.md`. `/content` is ephemeral Colab scratch — it is wiped with the runtime, "
            "so nothing here touches the disk-location question for the Mac.\n\n"
            "Re-running is safe: files already present at the right size are skipped, so a "
            "disconnect resumes rather than restarting."),
        _code(
            "DATA_ROOT = '/content/sen1floods11'\n"
            "!python scripts/download_sen1floods11.py --dest $DATA_ROOT \\\n"
            "    --json-out results/runs/sen1floods11_download.json\n"
        ),
        _code(
            "from pathlib import Path\n"
            "tifs = list(Path(DATA_ROOT).rglob('*.tif'))\n"
            "csvs = list(Path(DATA_ROOT).rglob('*.csv'))\n"
            "print(len(tifs), 'tif files,', len(csvs), 'split csvs')\n"
            "assert len(tifs) == 892, f'expected 892 tifs (446 S2Hand + 446 LabelHand), got {len(tifs)}'\n"
            "assert len(csvs) == 4, f'expected 4 split csvs, got {len(csvs)}'\n"
            "print('dataset matches the survey in DATA.md')\n"
        ),
        _md("## 7. Evaluate the 300M teacher — **the M0 gate**\n\n"
            "This produces the number the whole project is gated on.\n\n"
            "`--inference resize` mirrors the official recipe: the datamodule's own "
            "`albumentations.Resize(224,224)` is applied to image **and** mask, so metrics are "
            "computed at 224 against a downsampled mask. That is what the published recipe did, "
            "which is why it is the right mode for *reproducing* a published number.\n\n"
            "**Before comparing:** read the published figure at its source and record *which "
            "mIoU definition the source states* alongside the number. Macro mIoU, IoU_water "
            "alone, and micro-averaged IoU differ by more than the proposed tolerance on a "
            "2-class problem with this much class imbalance. A tolerance applied across two "
            "different definitions is not a gate.\n\n"
            "Do not adjust the tolerance after seeing this number."),
        _code(
            "!python train/eval.py --data-root $DATA_ROOT --split test \\\n"
            "    --inference resize --out results/runs/teacher_eval.json\n"
            "import json; print(json.dumps(json.load(open('results/runs/teacher_eval.json')), indent=2))\n"
        ),
        _code(
            "!mkdir -p $DRIVE/runs && cp results/runs/teacher_eval.json $DRIVE/runs/\n"
            "print('copied teacher_eval.json to Drive')\n"
        ),
        _md("## 8. Cache the teacher's test logits\n\nfp16 plus a manifest with per-file "
            "SHA-256, so the M2 distillation run can prove which logits it consumed."),
        _code(
            "!python train/cache_logits.py --data-root $DATA_ROOT --split test \\\n"
            "    --inference resize --out-dir $DRIVE/logits/test\n"
            "!ls $DRIVE/logits/test | head -5\n"
        ),
        _md("---\n\nWhen these cells have run, bring `teacher_eval.json` back to the Mac and "
            "record the comparison in `RESULTS.md` — with the published figure's URL, not a "
            "remembered number."),
    ]
    return {
        "cells": cells,
        "metadata": {
            "colab": {"provenance": [], "name": "minispatial bootstrap"},
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 0,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--commit", default=None, help="commit to pin (default: current HEAD)")
    parser.add_argument("--repo-url", default=REPO_URL)
    parser.add_argument("--out", type=Path, default=OUT)
    parser.add_argument("--dry-run", action="store_true", help="report only; write nothing")
    args = parser.parse_args(argv)

    commit = args.commit or _current_commit()
    notebook = build(commit, args.repo_url)

    if args.dry_run:
        print(f"[dry-run] would write {args.out} pinned to {commit} "
              f"({len(notebook['cells'])} cells)")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(notebook, indent=1) + "\n")
    print(f"wrote {args.out.relative_to(REPO_ROOT)} pinned to {commit} "
          f"({len(notebook['cells'])} cells)")
    if commit == "UNKNOWN":
        print("WARNING: HEAD could not be resolved; the notebook is not pinned.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
