#!/usr/bin/env python
"""minispatial Kaggle kernel -- training run.

GENERATED by scripts/make_kaggle_kernel.py; do not edit by hand. Pinned commit: 9231c39958d4e76da0c6f320f236515124db37ea
Config: train/configs/unet_small_lr1e-3.yaml
"""
import hashlib, json, os, platform, shutil, subprocess, sys, time
from pathlib import Path

COMMIT = '9231c39958d4e76da0c6f320f236515124db37ea'
REPO = 'https://github.com/AmeyaKI/minispatial.git'
CONFIG = 'train/configs/unet_small_lr1e-3.yaml'
RUN_NAME = 'unet_small_lr1e-3'
SMOKE = False
SRC = Path("/kaggle/tmp/minispatial")
DATA = Path("/kaggle/tmp/sen1floods11")
OUT = Path("/kaggle/working")
T0 = time.time()


def sh(*cmd, cwd=None, check=True):
    print("+", " ".join(cmd), flush=True)
    return subprocess.run(list(cmd), cwd=cwd, check=check)


def step(msg):
    print(f"\n=== [{time.time() - T0:7.1f}s] {msg}", flush=True)


step("runtime")
print("python", platform.python_version())
subprocess.run(["nvidia-smi", "--query-gpu=name,memory.total,driver_version", "--format=csv,noheader"], check=False)

step("clone pinned commit")
SRC.parent.mkdir(parents=True, exist_ok=True)
if not SRC.exists():
    sh("git", "clone", "-q", REPO, str(SRC))
sh("git", "fetch", "-q", "origin", cwd=SRC)
sh("git", "checkout", "-q", COMMIT, cwd=SRC)
sh("git", "rev-parse", "HEAD", cwd=SRC)

step("install (pinned from uv.lock except the CUDA stack)")
sh(sys.executable, "-m", "pip", "install", "-q", "-c", "kaggle/constraints.txt", "-e", ".[train]", cwd=SRC)
import importlib.metadata as md  # noqa: E402
versions = {p: md.version(p) for p in ("torch", "terratorch", "lightning", "numpy", "albumentations", "rasterio")}
print(json.dumps(versions, indent=2))

step("dataset -> /kaggle/tmp (scratch, not saved as output)")
sh(sys.executable, "scripts/download_sen1floods11.py", "--dest", str(DATA), cwd=SRC)
n_tif = len(list(DATA.rglob("*.tif"))); n_txt = len(list(DATA.rglob("*.txt")))
print(f"{n_tif} tifs, {n_txt} split txts")
assert n_tif == 892 and n_txt == 4, "dataset incomplete; refusing to train on a partial download"

step("train")
# ONE GPU (D030 amendment, 2026-10-02): Kaggle's T4 machine exposes two GPUs and Lightning's
# `devices: auto` would launch DDP across both, changing the effective batch size and crashing
# rank 1 in terratorch's validation plotting (dummy logger). The recipe is single-device.
sh(sys.executable, "train/train.py", "--config", CONFIG, 
   "--", "--trainer.devices", "1", "--data.init_args.data_root", str(DATA), cwd=SRC)

step("collect outputs + checksum manifest")
run_dir = SRC / "results" / "runs" / "train" / RUN_NAME
dest = OUT / RUN_NAME
if dest.exists():
    shutil.rmtree(dest)
shutil.copytree(run_dir, dest)
files = {}
for p in sorted(dest.rglob("*")):
    if p.is_file():
        files[str(p.relative_to(dest))] = {"sha256": hashlib.sha256(p.read_bytes()).hexdigest(), "bytes": p.stat().st_size}
manifest = {
    "kind": "kaggle_train_output_manifest",
    "run_name": RUN_NAME, "smoke": SMOKE, "config": CONFIG, "commit": COMMIT,
    "host": "kaggle", "python": platform.python_version(), "versions": versions,
    "gpu": subprocess.run(["nvidia-smi", "--query-gpu=name", "--format=csv,noheader"],
                          capture_output=True, text=True, check=False).stdout.strip() or None,
    "wall_seconds": round(time.time() - T0, 1),
    "files": files,
}
(OUT / f"{RUN_NAME}_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
print(json.dumps({k: v for k, v in manifest.items() if k != "files"}, indent=2))
print(f"{len(files)} files in {dest}")
step("done")
